
name: Testing Workflow
on:
  push:
  workflow_dispatch:
jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Test on Scratch Org
      uses: tythonco/actions-sfdx@cicd-enhancements
      with:
        auth_file_key: ${{ secrets.AUTH_FILE_KEY }}
        command: test-scratch
